# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170426_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_next',
            new_name='choice_text',
        ),
    ]
